### ISSUE TITLE
Use Medium/phantomjs

### ISSUE THREAD

**Issue by Arkni** [ponyfoo/ponyfoo#36]
Hi @bevacqua 

I noticed in [`package.json`](https://github.com/ponyfoo/ponyfoo/blob/master/package.json#L167) that you're using a fork in order to use `PhantomJS 2.x`. But the last version of [`Medium/phantomjs`](https://github.com/Medium/phantomjs) (`2.1.x`) can now install the latest version of `PhantomJS` (aka `2.1.1`), so no need to use a custom fork.

I can send a PR if you do agree with that.

**Comment by bevacqua** [comment]
Not terribly concerned about this, `phantomjs` is only used during production builds IIRC

**Comment by Arkni** [comment]
I know, but my point mainly related to #35 (even though the OP resolved his issue). Also, it's better to use the official binaries instead of community compiled ones.

Feel free to close this if you see it as unneeded.

**Comment by bevacqua** [comment]
By all means, do make a PR. I'll give it a shot!

**Comment by Arkni** [comment]
See #37
