### ISSUE TITLE
Pony Foo Weekly not displaying nicely in Inoreader

### ISSUE THREAD

**Issue by tomitm** [ponyfoo/ponyfoo#39]
Comparing to your site, it looks like classes are stripped. :confused: 

![image](https://cloud.githubusercontent.com/assets/4513759/13892813/197144ae-ed17-11e5-8855-186df2b2b895.png)
![image](https://cloud.githubusercontent.com/assets/4513759/13892821/2f88df2c-ed17-11e5-974d-aa23a55f06eb.png)

![image](https://cloud.githubusercontent.com/assets/4513759/13892828/39c67490-ed17-11e5-92aa-bd72b2711986.png)

![image](https://cloud.githubusercontent.com/assets/4513759/13892842/5521f052-ed17-11e5-9f95-9189befcaff0.png)

Chrome 51.0.2679.0 dev

**Comment by bevacqua** [comment]
Ew. Does the same happen to articles?

**Comment by tomitm** [comment]
Nope, just the weekly. I think that's because you don't use many classes on your articles, so they end up faring much better.

![image](https://cloud.githubusercontent.com/assets/4513759/13893407/44b78ba6-ed1b-11e5-874a-9317a8472fe7.png)

Although, there's no syntax highlighting unlike on your site.

**Comment by bevacqua** [comment]
Right. Articles are much simpler in layouting, that's intentional. The weekly's content pretty much needs to have complicated styles. I guess I could use more `&nbsp;`-like layouting, but the code would be pretty hideous

**Comment by bevacqua** [comment]
Could you tell me if this is fixed? Emoji in the RSS feed now inline the image width/height

**Comment by tomitm** [comment]
I'm not sure if I'm looking at a cached version or not, last week's issue is still showing with the problem.

I'll let you know when this week's issue is posted!

**Comment by bevacqua** [comment]
Meh. This is pretty much unfixable.

**Comment by tomitm** [comment]
This week feels like it's looking better.

![image](https://cloud.githubusercontent.com/assets/4513759/15939761/12e835d6-2e2e-11e6-96cf-8547f8c36894.png)
![image](https://cloud.githubusercontent.com/assets/4513759/15939770/21188156-2e2e-11e6-9b14-650237eeb4e7.png)
![image](https://cloud.githubusercontent.com/assets/4513759/15939780/289c7b58-2e2e-11e6-9185-95062719d23a.png)
![image](https://cloud.githubusercontent.com/assets/4513759/15939788/30e03246-2e2e-11e6-920f-62cc07fb47bf.png)

No longer seeing the 1-character lines, at least. Just looks like image sizes are being messed up. The sw infographic has an inline style `max-width: 1345px; height: auto; object-fit: contain;`. Seems like the problem is also visible on [Feedburner's page](https://feeds.feedburner.com/ponyfooweekly).

Pretty good so far for being unfixable. 👌

**Comment by bevacqua** [comment]
Most problems go away with an `img { max-width: 100% }` rule which I almost always use everywhere. Every reader does their own thing, though, so styles are very hard.

**Comment by bevacqua** [comment]
@tomitm This should have vastly improved after [`42596829`](https://github.com/ponyfoo/ponyfoo/commit/425968294edf79cabf9261472648f81a7170884e). See also: https://feeds.feedburner.com/ponyfooweekly

**Comment by tomitm** [comment]
@bevacqua So, unfortunately your changes haven't made much of a difference. 😦

I contacted Inoreader to see if there'd be any chance they'd fix it on their end (since they're converting 100% to a px value), and this is what they responded with:

> We’ve managed to investigate what is the reason about this issues.

> It's just not properly formatted.

> Actually the feed contains too many additional stile attributes and most of them are removed for security and stability.

> This list was fine-tuned over the years and we prefer to keep it that way. I'm sure it's the same story in other RSS readers.

> The feedvalidator check also is telling that there are style attributes containing potentially dangerous content - http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Ffeeds.feedburner.com%2Fponyfooweekly

From the validator output, this one stands out to me:

> line 2, column 0: style attribute contains potentially dangerous content: -moz-box-sizing: inherit; -webkit-box-sizing: inherit; box-sizing: inherit; font-family: 'Helvetica Neue',HelveticaNeue,TeXGyreHeros,FreeSans,'Nimbus Sans L','Liberation Sans',Helvetica,Arial,sans-serif; (4619 occurrences)

So maybe inlining the CSS was the wrong direction? ¯\\\_(ツ)_/¯

Just figured I'd let you know in case you were interested in figuring it out. Don't worry about it if it's too much of a problem! 😄
