### ISSUE TITLE
<p> inside <h1> causes incorrect line spacing

### ISSUE THREAD

**Issue by simevidas** [ponyfoo/ponyfoo#41]
Note that `<p>` inside heading elements isn’t even allowed, according to the standard.

![foo](https://cloud.githubusercontent.com/assets/716405/17903303/56381004-696b-11e6-910f-ecca1ca84829.png)

**Comment by bevacqua** [comment]
Will look into changing this 👍

**Comment by bevacqua** [comment]
Fixed and also updated in `ponyfoo/articles` 🚀
